import { Game, PlayerProfile } from "../types/basketball";

export const BUNDLED_SOMISA_DATA: {
  appName?: string;
  version?: string;
  exportDate?: string;
  totalGames?: number;
  roster: PlayerProfile[];
  games: Game[];
} = {
  "appName": "Club SOMISA Básquetbol",
  "version": "4.0.0",
  "exportDate": "2026-10-06T17:17:24.101Z",
  "totalGames": 5,
  "roster": [
    {
      "id": "som_p1",
      "name": "PAEZ, FELIPE",
      "number": 1,
      "position": "Base",
      "isCaptain": false,
      "active": true
    },
    {
      "id": "som_p2",
      "name": "PEDEMONTE, JUAN PABLO",
      "number": 2,
      "position": "Alero",
      "isCaptain": false,
      "active": true
    },
    {
      "id": "som_p3",
      "name": "ZACCHERINI ROMERO, FABRICIO MATIAS",
      "number": 4,
      "position": "Escolta",
      "isCaptain": false,
      "active": true
    },
    {
      "id": "som_p4",
      "name": "GONZALEZ ROVEDA, LUCIO",
      "number": 5,
      "position": "Alero",
      "isCaptain": false,
      "active": true
    },
    {
      "id": "som_p5",
      "name": "DIAZ, JAIME",
      "number": 7,
      "position": "Escolta",
      "isCaptain": false,
      "active": true
    },
    {
      "id": "som_p6",
      "name": "BUALO, AGUSTIN",
      "number": 8,
      "position": "Base",
      "isCaptain": false,
      "active": true
    },
    {
      "id": "som_p7",
      "name": "BROVARONE, FAUSTINO",
      "number": 9,
      "position": "Escolta",
      "isCaptain": false,
      "active": true
    },
    {
      "id": "som_p8",
      "name": "VITANGELI, SANTINO",
      "number": 10,
      "position": "Base",
      "isCaptain": false,
      "active": true
    },
    {
      "id": "som_p9",
      "name": "RATTERO, RAMIRO",
      "number": 11,
      "position": "Ala-Pívot",
      "isCaptain": false,
      "active": true
    },
    {
      "id": "som_p10",
      "name": "URANGA, SEBASTIAN",
      "number": 12,
      "position": "Pívot",
      "isCaptain": true,
      "active": true
    },
    {
      "id": "som_p11",
      "name": "MASCAZZINI, ALEJO BENJAMIN",
      "number": 20,
      "position": "Alero",
      "isCaptain": false,
      "active": true
    },
    {
      "id": "som_p12",
      "name": "ANDOLLO, SEBASTIAN",
      "number": 33,
      "position": "Pívot",
      "isCaptain": false,
      "active": true
    }
  ],
  "games": [
    {
      "id": "match_excel_1791210980517",
      "title": "SOMISA (San Nicolas) vs BELGRANO (San Nicolas)",
      "date": "2026-10-05",
      "competition": "LIGA PCIAL FBB (Masculino 2026)",
      "season": "2026",
      "homeAway": "home",
      "myTeamName": "SOMISA (San Nicolas)",
      "opponentName": "BELGRANO (San Nicolas)",
      "scoreMyTeam": 79,
      "scoreOpponent": 50,
      "notes": "Importado desde planilla Excel oficial.",
      "rows": [
        {
          "id": "row_somisa_1_1791210974197_0.2529039497077311",
          "playerNumber": 1,
          "playerName": "PAEZ, FELIPE",
          "playerPosition": "Alero",
          "min": "00:00",
          "minSeconds": 0,
          "tc": 0,
          "ti": 0,
          "tiPct": 0,
          "c3p": 0,
          "i3p": 0,
          "pct3p": 0,
          "ar3p": 0,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 0,
          "tsPct": 0,
          "tovPct": 0,
          "rd": 0,
          "ro": 0,
          "rt": 0,
          "as": 0,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 0,
          "fpr": 0,
          "pt": 0,
          "ptsTot": 0
        },
        {
          "id": "row_somisa_2_1791210974197_0.694387282022075",
          "playerNumber": 2,
          "playerName": "PEDEMONTE, JUAN PABLO",
          "playerPosition": "Alero",
          "min": "28:24",
          "minSeconds": 1704,
          "tc": 3,
          "ti": 3,
          "tiPct": 100,
          "c3p": 4,
          "i3p": 8,
          "pct3p": 50,
          "ar3p": 72.7,
          "tlc": 3,
          "tli": 3,
          "tlPct": 100,
          "ftr": 27.27,
          "efgPct": 81.82,
          "tsPct": 85.23,
          "tovPct": 0,
          "rd": 7,
          "ro": 1,
          "rt": 8,
          "as": 0,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 4,
          "fpr": 2,
          "pt": 21,
          "ptsTot": 23
        },
        {
          "id": "row_somisa_4_1791210974197_0.4669500996448598",
          "playerNumber": 4,
          "playerName": "ZACCHERINI ROMERO, FABRICIO MATIAS",
          "playerPosition": "Alero",
          "min": "00:35",
          "minSeconds": 35,
          "tc": 0,
          "ti": 0,
          "tiPct": 0,
          "c3p": 0,
          "i3p": 0,
          "pct3p": 0,
          "ar3p": 0,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 0,
          "tsPct": 0,
          "tovPct": 0,
          "rd": 0,
          "ro": 0,
          "rt": 0,
          "as": 0,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 0,
          "fpr": 0,
          "pt": 0,
          "ptsTot": 0
        },
        {
          "id": "row_somisa_5_1791210974197_0.12202951143049545",
          "playerNumber": 5,
          "playerName": "GONZALEZ ROVEDA, LUCIO",
          "playerPosition": "Base",
          "min": "31:31",
          "minSeconds": 1891,
          "tc": 2,
          "ti": 6,
          "tiPct": 33.33,
          "c3p": 3,
          "i3p": 7,
          "pct3p": 42.86,
          "ar3p": 53.8,
          "tlc": 3,
          "tli": 5,
          "tlPct": 60,
          "ftr": 38.46,
          "efgPct": 50,
          "tsPct": 52.63,
          "tovPct": 11.63,
          "rd": 7,
          "ro": 0,
          "rt": 7,
          "as": 2,
          "rec": 3,
          "per": 2,
          "tap": 0,
          "fpc": 1,
          "fpr": 4,
          "pt": 16,
          "ptsTot": 19
        },
        {
          "id": "row_somisa_8_1791210974197_0.809531751310087",
          "playerNumber": 8,
          "playerName": "BUALO, AGUSTIN",
          "playerPosition": "Base",
          "min": "19:24",
          "minSeconds": 1164,
          "tc": 1,
          "ti": 2,
          "tiPct": 50,
          "c3p": 0,
          "i3p": 4,
          "pct3p": 0,
          "ar3p": 66.7,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 16.67,
          "tsPct": 16.67,
          "tovPct": 33.33,
          "rd": 3,
          "ro": 0,
          "rt": 3,
          "as": 4,
          "rec": 1,
          "per": 3,
          "tap": 0,
          "fpc": 0,
          "fpr": 1,
          "pt": 2,
          "ptsTot": 3
        },
        {
          "id": "row_somisa_9_1791210974197_0.9458165154845944",
          "playerNumber": 9,
          "playerName": "BROVARONE, FAUSTINO",
          "playerPosition": "Base",
          "min": "08:26",
          "minSeconds": 506,
          "tc": 0,
          "ti": 1,
          "tiPct": 0,
          "c3p": 0,
          "i3p": 1,
          "pct3p": 0,
          "ar3p": 50,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 0,
          "tsPct": 0,
          "tovPct": 0,
          "rd": 3,
          "ro": 0,
          "rt": 3,
          "as": 0,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 0,
          "fpr": 0,
          "pt": 0,
          "ptsTot": 1
        },
        {
          "id": "row_somisa_11_1791210974197_0.4889772300661599",
          "playerNumber": 11,
          "playerName": "RATTERO, RAMIRO",
          "playerPosition": "Alero",
          "min": "30:00",
          "minSeconds": 1800,
          "tc": 5,
          "ti": 7,
          "tiPct": 71.43,
          "c3p": 1,
          "i3p": 6,
          "pct3p": 16.67,
          "ar3p": 46.2,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 50,
          "tsPct": 50,
          "tovPct": 7.14,
          "rd": 4,
          "ro": 1,
          "rt": 5,
          "as": 5,
          "rec": 1,
          "per": 1,
          "tap": 0,
          "fpc": 3,
          "fpr": 1,
          "pt": 13,
          "ptsTot": 14
        },
        {
          "id": "row_somisa_12_1791210974197_0.5236448455288709",
          "playerNumber": 12,
          "playerName": "URANGA, SEBASTIAN",
          "playerPosition": "Pívot",
          "min": "23:46",
          "minSeconds": 1426,
          "tc": 2,
          "ti": 2,
          "tiPct": 100,
          "c3p": 0,
          "i3p": 1,
          "pct3p": 0,
          "ar3p": 33.3,
          "tlc": 2,
          "tli": 3,
          "tlPct": 66.67,
          "ftr": 100,
          "efgPct": 66.67,
          "tsPct": 69.44,
          "tovPct": 18.8,
          "rd": 5,
          "ro": 1,
          "rt": 6,
          "as": 3,
          "rec": 1,
          "per": 1,
          "tap": 1,
          "fpc": 1,
          "fpr": 4,
          "pt": 6,
          "ptsTot": 16
        },
        {
          "id": "row_somisa_13_1791210974197_0.7761126581241714",
          "playerNumber": 13,
          "playerName": "VASSOLO, EMILIANO",
          "playerPosition": "Alero",
          "min": "18:08",
          "minSeconds": 1088,
          "tc": 0,
          "ti": 3,
          "tiPct": 0,
          "c3p": 0,
          "i3p": 1,
          "pct3p": 0,
          "ar3p": 25,
          "tlc": 2,
          "tli": 2,
          "tlPct": 100,
          "ftr": 50,
          "efgPct": 0,
          "tsPct": 20.49,
          "tovPct": 0,
          "rd": 3,
          "ro": 1,
          "rt": 4,
          "as": 5,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 4,
          "fpr": 1,
          "pt": 2,
          "ptsTot": 4
        },
        {
          "id": "row_somisa_20_1791210974197_0.4062408972291124",
          "playerNumber": 20,
          "playerName": "MASCAZZINI, ALEJO BENJAMIN",
          "playerPosition": "Alero",
          "min": "00:35",
          "minSeconds": 35,
          "tc": 0,
          "ti": 0,
          "tiPct": 0,
          "c3p": 0,
          "i3p": 0,
          "pct3p": 0,
          "ar3p": 0,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 0,
          "tsPct": 0,
          "tovPct": 0,
          "rd": 0,
          "ro": 0,
          "rt": 0,
          "as": 0,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 0,
          "fpr": 0,
          "pt": 0,
          "ptsTot": 0
        },
        {
          "id": "row_somisa_33_1791210974197_0.02729134346190676",
          "playerNumber": 33,
          "playerName": "ANDOLLO, SEBASTIAN",
          "playerPosition": "Alero",
          "min": "09:08",
          "minSeconds": 548,
          "tc": 0,
          "ti": 0,
          "tiPct": 0,
          "c3p": 0,
          "i3p": 1,
          "pct3p": 0,
          "ar3p": 100,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 0,
          "tsPct": 0,
          "tovPct": 66.67,
          "rd": 2,
          "ro": 0,
          "rt": 2,
          "as": 0,
          "rec": 0,
          "per": 2,
          "tap": 0,
          "fpc": 0,
          "fpr": 0,
          "pt": 0,
          "ptsTot": -1
        },
        {
          "id": "row_somisa_88_1791210974197_0.04321409498403228",
          "playerNumber": 88,
          "playerName": "MENA, SEBASTIAN ALEJANDRO",
          "playerPosition": "Alero",
          "min": "29:57",
          "minSeconds": 1797,
          "tc": 6,
          "ti": 7,
          "tiPct": 85.71,
          "c3p": 2,
          "i3p": 2,
          "pct3p": 100,
          "ar3p": 22.2,
          "tlc": 1,
          "tli": 2,
          "tlPct": 50,
          "ftr": 22.22,
          "efgPct": 100,
          "tsPct": 96.15,
          "tovPct": 9.19,
          "rd": 4,
          "ro": 2,
          "rt": 6,
          "as": 4,
          "rec": 3,
          "per": 1,
          "tap": 1,
          "fpc": 3,
          "fpr": 1,
          "pt": 19,
          "ptsTot": 28
        }
      ],
      "opponentStats": {
        "pts": 50,
        "tc": 8,
        "ti": 28,
        "c3p": 9,
        "i3p": 34,
        "tlc": 7,
        "tli": 14,
        "rd": 29,
        "ro": 6,
        "as": 10,
        "rec": 7,
        "per": 14,
        "tap": 1,
        "fpc": 16
      },
      "shots": []
    },
    {
      "id": "match_excel_1790960078321",
      "title": "SOMISA (San Nicolas) vs PORTEÑO (Chacabuco)",
      "date": "2026-10-02",
      "competition": "LIGA PCIAL FBB (Masculino 2026)",
      "season": "2026",
      "homeAway": "home",
      "myTeamName": "SOMISA (San Nicolas)",
      "opponentName": "PORTEÑO (Chacabuco)",
      "scoreMyTeam": 85,
      "scoreOpponent": 56,
      "notes": "Importado desde planilla Excel oficial.",
      "rows": [
        {
          "id": "row_somisa_1_1790960077406_0.4553163985123293",
          "playerNumber": 1,
          "playerName": "PAEZ, FELIPE",
          "playerPosition": "Alero",
          "min": "02:37",
          "minSeconds": 157,
          "tc": 0,
          "ti": 0,
          "tiPct": 0,
          "c3p": 1,
          "i3p": 1,
          "pct3p": 100,
          "ar3p": 100,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 150,
          "tsPct": 150,
          "tovPct": 0,
          "rd": 0,
          "ro": 0,
          "rt": 0,
          "as": 0,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 0,
          "fpr": 0,
          "pt": 3,
          "ptsTot": 3
        },
        {
          "id": "row_somisa_2_1790960077406_0.5341763010714599",
          "playerNumber": 2,
          "playerName": "PEDEMONTE, JUAN PABLO",
          "playerPosition": "Alero",
          "min": "21:12",
          "minSeconds": 1272,
          "tc": 1,
          "ti": 1,
          "tiPct": 100,
          "c3p": 2,
          "i3p": 5,
          "pct3p": 40,
          "ar3p": 83.3,
          "tlc": 1,
          "tli": 3,
          "tlPct": 33.33,
          "ftr": 50,
          "efgPct": 66.67,
          "tsPct": 61.48,
          "tovPct": 21.46,
          "rd": 5,
          "ro": 0,
          "rt": 5,
          "as": 0,
          "rec": 0,
          "per": 2,
          "tap": 0,
          "fpc": 2,
          "fpr": 1,
          "pt": 9,
          "ptsTot": 6
        },
        {
          "id": "row_somisa_4_1790960077406_0.36220364609918987",
          "playerNumber": 4,
          "playerName": "ZACCHERINI ROMERO, FABRICIO MATIAS",
          "playerPosition": "Alero",
          "min": "09:28",
          "minSeconds": 568,
          "tc": 0,
          "ti": 1,
          "tiPct": 0,
          "c3p": 0,
          "i3p": 2,
          "pct3p": 0,
          "ar3p": 66.7,
          "tlc": 2,
          "tli": 2,
          "tlPct": 100,
          "ftr": 66.67,
          "efgPct": 0,
          "tsPct": 25.77,
          "tovPct": 0,
          "rd": 3,
          "ro": 0,
          "rt": 3,
          "as": 0,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 0,
          "fpr": 1,
          "pt": 2,
          "ptsTot": 3
        },
        {
          "id": "row_somisa_5_1790960077406_0.6709922988520013",
          "playerNumber": 5,
          "playerName": "GONZALEZ ROVEDA, LUCIO",
          "playerPosition": "Base",
          "min": "30:32",
          "minSeconds": 1832,
          "tc": 7,
          "ti": 9,
          "tiPct": 77.78,
          "c3p": 2,
          "i3p": 4,
          "pct3p": 50,
          "ar3p": 30.8,
          "tlc": 2,
          "tli": 2,
          "tlPct": 100,
          "ftr": 15.38,
          "efgPct": 76.92,
          "tsPct": 79.25,
          "tovPct": 0,
          "rd": 9,
          "ro": 0,
          "rt": 9,
          "as": 2,
          "rec": 2,
          "per": 0,
          "tap": 1,
          "fpc": 1,
          "fpr": 2,
          "pt": 22,
          "ptsTot": 32
        },
        {
          "id": "row_somisa_8_1790960077406_0.7199491046590474",
          "playerNumber": 8,
          "playerName": "VITANGELI, SANTINO",
          "playerPosition": "Base",
          "min": "10:40",
          "minSeconds": 640,
          "tc": 2,
          "ti": 2,
          "tiPct": 100,
          "c3p": 0,
          "i3p": 1,
          "pct3p": 0,
          "ar3p": 33.3,
          "tlc": 1,
          "tli": 1,
          "tlPct": 100,
          "ftr": 33.33,
          "efgPct": 66.67,
          "tsPct": 72.67,
          "tovPct": 0,
          "rd": 0,
          "ro": 1,
          "rt": 1,
          "as": 1,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 2,
          "fpr": 1,
          "pt": 5,
          "ptsTot": 5
        },
        {
          "id": "row_somisa_9_1790960077406_0.6843336301403117",
          "playerNumber": 9,
          "playerName": "BROVARONE, FAUSTINO",
          "playerPosition": "Base",
          "min": "21:23",
          "minSeconds": 1283,
          "tc": 2,
          "ti": 3,
          "tiPct": 66.67,
          "c3p": 2,
          "i3p": 3,
          "pct3p": 66.67,
          "ar3p": 50,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 83.33,
          "tsPct": 83.33,
          "tovPct": 14.29,
          "rd": 3,
          "ro": 0,
          "rt": 3,
          "as": 1,
          "rec": 1,
          "per": 1,
          "tap": 0,
          "fpc": 2,
          "fpr": 0,
          "pt": 10,
          "ptsTot": 10
        },
        {
          "id": "row_somisa_11_1790960077406_0.030208893682413973",
          "playerNumber": 11,
          "playerName": "RATTERO, RAMIRO",
          "playerPosition": "Alero",
          "min": "23:54",
          "minSeconds": 1434,
          "tc": 3,
          "ti": 4,
          "tiPct": 75,
          "c3p": 1,
          "i3p": 3,
          "pct3p": 33.33,
          "ar3p": 42.9,
          "tlc": 1,
          "tli": 2,
          "tlPct": 50,
          "ftr": 28.57,
          "efgPct": 64.29,
          "tsPct": 63.45,
          "tovPct": 20.24,
          "rd": 4,
          "ro": 2,
          "rt": 6,
          "as": 2,
          "rec": 2,
          "per": 2,
          "tap": 0,
          "fpc": 4,
          "fpr": 2,
          "pt": 10,
          "ptsTot": 10
        },
        {
          "id": "row_somisa_12_1790960077406_0.41031263207626756",
          "playerNumber": 12,
          "playerName": "URANGA, SEBASTIAN",
          "playerPosition": "Pívot",
          "min": "19:34",
          "minSeconds": 1174,
          "tc": 3,
          "ti": 6,
          "tiPct": 50,
          "c3p": 1,
          "i3p": 1,
          "pct3p": 100,
          "ar3p": 14.3,
          "tlc": 1,
          "tli": 2,
          "tlPct": 50,
          "ftr": 28.57,
          "efgPct": 64.29,
          "tsPct": 63.45,
          "tovPct": 20.24,
          "rd": 4,
          "ro": 0,
          "rt": 4,
          "as": 2,
          "rec": 0,
          "per": 2,
          "tap": 1,
          "fpc": 1,
          "fpr": 2,
          "pt": 10,
          "ptsTot": 12
        },
        {
          "id": "row_somisa_13_1790960077406_0.6795037995654063",
          "playerNumber": 13,
          "playerName": "VASSOLO, EMILIANO",
          "playerPosition": "Alero",
          "min": "17:46",
          "minSeconds": 1066,
          "tc": 3,
          "ti": 5,
          "tiPct": 60,
          "c3p": 0,
          "i3p": 0,
          "pct3p": 0,
          "ar3p": 0,
          "tlc": 1,
          "tli": 2,
          "tlPct": 50,
          "ftr": 40,
          "efgPct": 60,
          "tsPct": 59.52,
          "tovPct": 14.53,
          "rd": 5,
          "ro": 1,
          "rt": 6,
          "as": 3,
          "rec": 0,
          "per": 1,
          "tap": 0,
          "fpc": 3,
          "fpr": 3,
          "pt": 7,
          "ptsTot": 12
        },
        {
          "id": "row_somisa_20_1790960077406_0.31637379233922025",
          "playerNumber": 20,
          "playerName": "MASCAZZINI, ALEJO BENJAMIN",
          "playerPosition": "Alero",
          "min": "02:49",
          "minSeconds": 169,
          "tc": 0,
          "ti": 0,
          "tiPct": 0,
          "c3p": 0,
          "i3p": 0,
          "pct3p": 0,
          "ar3p": 0,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 0,
          "tsPct": 0,
          "tovPct": 0,
          "rd": 1,
          "ro": 0,
          "rt": 1,
          "as": 0,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 0,
          "fpr": 0,
          "pt": 0,
          "ptsTot": 1
        },
        {
          "id": "row_somisa_33_1790960077406_0.6432456833290798",
          "playerNumber": 33,
          "playerName": "ANDOLLO, SEBASTIAN",
          "playerPosition": "Alero",
          "min": "14:17",
          "minSeconds": 857,
          "tc": 1,
          "ti": 1,
          "tiPct": 100,
          "c3p": 0,
          "i3p": 1,
          "pct3p": 0,
          "ar3p": 50,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 50,
          "tsPct": 50,
          "tovPct": 33.33,
          "rd": 3,
          "ro": 2,
          "rt": 5,
          "as": 3,
          "rec": 0,
          "per": 1,
          "tap": 0,
          "fpc": 2,
          "fpr": 0,
          "pt": 2,
          "ptsTot": 6
        },
        {
          "id": "row_somisa_88_1790960077406_0.8918805574787323",
          "playerNumber": 88,
          "playerName": "MENA, SEBASTIAN ALEJANDRO",
          "playerPosition": "Alero",
          "min": "25:42",
          "minSeconds": 1542,
          "tc": 1,
          "ti": 4,
          "tiPct": 25,
          "c3p": 0,
          "i3p": 1,
          "pct3p": 0,
          "ar3p": 20,
          "tlc": 3,
          "tli": 4,
          "tlPct": 75,
          "ftr": 80,
          "efgPct": 20,
          "tsPct": 36.98,
          "tovPct": 12.89,
          "rd": 2,
          "ro": 0,
          "rt": 2,
          "as": 4,
          "rec": 0,
          "per": 1,
          "tap": 0,
          "fpc": 1,
          "fpr": 3,
          "pt": 5,
          "ptsTot": 7
        }
      ],
      "opponentStats": {
        "pts": 56,
        "tc": 12,
        "ti": 31,
        "c3p": 9,
        "i3p": 35,
        "tlc": 5,
        "tli": 12,
        "rd": 19,
        "ro": 11,
        "as": 10,
        "rec": 3,
        "per": 9,
        "tap": 3,
        "fpc": 18
      },
      "shots": []
    },
    {
      "id": "match_excel_1790960071564",
      "title": "SOMISA (San Nicolas) vs ARGENTINO (Pergamino)",
      "date": "2026-10-02",
      "competition": "LIGA PCIAL FBB (Masculino 2026)",
      "season": "2026",
      "homeAway": "home",
      "myTeamName": "SOMISA (San Nicolas)",
      "opponentName": "ARGENTINO (Pergamino)",
      "scoreMyTeam": 86,
      "scoreOpponent": 52,
      "notes": "Importado desde planilla Excel oficial.",
      "rows": [
        {
          "id": "row_somisa_1_1790960070570_0.6008406908732199",
          "playerNumber": 1,
          "playerName": "PAEZ, FELIPE",
          "playerPosition": "Alero",
          "min": "02:37",
          "minSeconds": 157,
          "tc": 0,
          "ti": 0,
          "tiPct": 0,
          "c3p": 0,
          "i3p": 0,
          "pct3p": 0,
          "ar3p": 0,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 0,
          "tsPct": 0,
          "tovPct": 0,
          "rd": 1,
          "ro": 0,
          "rt": 1,
          "as": 0,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 0,
          "fpr": 0,
          "pt": 0,
          "ptsTot": 1
        },
        {
          "id": "row_somisa_2_1790960070570_0.652558163761771",
          "playerNumber": 2,
          "playerName": "PEDEMONTE, JUAN PABLO",
          "playerPosition": "Alero",
          "min": "30:28",
          "minSeconds": 1828,
          "tc": 0,
          "ti": 0,
          "tiPct": 0,
          "c3p": 3,
          "i3p": 7,
          "pct3p": 42.86,
          "ar3p": 100,
          "tlc": 2,
          "tli": 4,
          "tlPct": 50,
          "ftr": 57.14,
          "efgPct": 64.29,
          "tsPct": 62.79,
          "tovPct": 18.59,
          "rd": 7,
          "ro": 1,
          "rt": 8,
          "as": 2,
          "rec": 1,
          "per": 2,
          "tap": 0,
          "fpc": 4,
          "fpr": 2,
          "pt": 11,
          "ptsTot": 11
        },
        {
          "id": "row_somisa_4_1790960070570_0.073015578436884",
          "playerNumber": 4,
          "playerName": "ZACCHERINI ROMERO, FABRICIO MATIAS",
          "playerPosition": "Alero",
          "min": "06:35",
          "minSeconds": 395,
          "tc": 1,
          "ti": 1,
          "tiPct": 100,
          "c3p": 1,
          "i3p": 1,
          "pct3p": 100,
          "ar3p": 50,
          "tlc": 2,
          "tli": 2,
          "tlPct": 100,
          "ftr": 100,
          "efgPct": 125,
          "tsPct": 121.53,
          "tovPct": 0,
          "rd": 2,
          "ro": 0,
          "rt": 2,
          "as": 1,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 1,
          "fpr": 1,
          "pt": 7,
          "ptsTot": 10
        },
        {
          "id": "row_somisa_5_1790960070570_0.8035759266955292",
          "playerNumber": 5,
          "playerName": "GONZALEZ ROVEDA, LUCIO",
          "playerPosition": "Base",
          "min": "26:50",
          "minSeconds": 1610,
          "tc": 7,
          "ti": 10,
          "tiPct": 70,
          "c3p": 0,
          "i3p": 5,
          "pct3p": 0,
          "ar3p": 33.3,
          "tlc": 6,
          "tli": 6,
          "tlPct": 100,
          "ftr": 40,
          "efgPct": 46.67,
          "tsPct": 56.69,
          "tovPct": 5.36,
          "rd": 5,
          "ro": 0,
          "rt": 5,
          "as": 1,
          "rec": 0,
          "per": 1,
          "tap": 1,
          "fpc": 1,
          "fpr": 3,
          "pt": 20,
          "ptsTot": 20
        },
        {
          "id": "row_somisa_8_1790960070570_0.17889374988742102",
          "playerNumber": 8,
          "playerName": "BUALO, AGUSTIN",
          "playerPosition": "Base",
          "min": "06:26",
          "minSeconds": 386,
          "tc": 0,
          "ti": 0,
          "tiPct": 0,
          "c3p": 0,
          "i3p": 2,
          "pct3p": 0,
          "ar3p": 100,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 0,
          "tsPct": 0,
          "tovPct": 0,
          "rd": 1,
          "ro": 0,
          "rt": 1,
          "as": 2,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 0,
          "fpr": 1,
          "pt": 0,
          "ptsTot": 2
        },
        {
          "id": "row_somisa_9_1790960070570_0.9436550101413506",
          "playerNumber": 9,
          "playerName": "BROVARONE, FAUSTINO",
          "playerPosition": "Base",
          "min": "21:32",
          "minSeconds": 1292,
          "tc": 1,
          "ti": 2,
          "tiPct": 50,
          "c3p": 3,
          "i3p": 5,
          "pct3p": 60,
          "ar3p": 71.4,
          "tlc": 1,
          "tli": 2,
          "tlPct": 50,
          "ftr": 28.57,
          "efgPct": 78.57,
          "tsPct": 76.14,
          "tovPct": 11.26,
          "rd": 1,
          "ro": 4,
          "rt": 5,
          "as": 0,
          "rec": 0,
          "per": 1,
          "tap": 0,
          "fpc": 1,
          "fpr": 1,
          "pt": 12,
          "ptsTot": 12
        },
        {
          "id": "row_somisa_11_1790960070570_0.3669827536107876",
          "playerNumber": 11,
          "playerName": "RATTERO, RAMIRO",
          "playerPosition": "Alero",
          "min": "23:13",
          "minSeconds": 1393,
          "tc": 2,
          "ti": 3,
          "tiPct": 66.67,
          "c3p": 3,
          "i3p": 7,
          "pct3p": 42.86,
          "ar3p": 70,
          "tlc": 2,
          "tli": 2,
          "tlPct": 100,
          "ftr": 20,
          "efgPct": 65,
          "tsPct": 68.93,
          "tovPct": 0,
          "rd": 0,
          "ro": 1,
          "rt": 1,
          "as": 1,
          "rec": 1,
          "per": 0,
          "tap": 0,
          "fpc": 0,
          "fpr": 2,
          "pt": 15,
          "ptsTot": 15
        },
        {
          "id": "row_somisa_12_1790960070570_0.4560704108012815",
          "playerNumber": 12,
          "playerName": "URANGA, SEBASTIAN",
          "playerPosition": "Pívot",
          "min": "13:51",
          "minSeconds": 831,
          "tc": 1,
          "ti": 1,
          "tiPct": 100,
          "c3p": 0,
          "i3p": 3,
          "pct3p": 0,
          "ar3p": 75,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 25,
          "tsPct": 25,
          "tovPct": 0,
          "rd": 3,
          "ro": 0,
          "rt": 3,
          "as": 2,
          "rec": 1,
          "per": 0,
          "tap": 0,
          "fpc": 2,
          "fpr": 0,
          "pt": 2,
          "ptsTot": 2
        },
        {
          "id": "row_somisa_13_1790960070570_0.5637808377119595",
          "playerNumber": 13,
          "playerName": "VASSOLO, EMILIANO",
          "playerPosition": "Alero",
          "min": "25:05",
          "minSeconds": 1505,
          "tc": 2,
          "ti": 4,
          "tiPct": 50,
          "c3p": 0,
          "i3p": 2,
          "pct3p": 0,
          "ar3p": 33.3,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 33.33,
          "tsPct": 33.33,
          "tovPct": 14.29,
          "rd": 6,
          "ro": 2,
          "rt": 8,
          "as": 6,
          "rec": 0,
          "per": 1,
          "tap": 0,
          "fpc": 1,
          "fpr": 2,
          "pt": 4,
          "ptsTot": 14
        },
        {
          "id": "row_somisa_20_1790960070570_0.9730572929905931",
          "playerNumber": 20,
          "playerName": "MASCAZZINI, ALEJO BENJAMIN",
          "playerPosition": "Alero",
          "min": "02:37",
          "minSeconds": 157,
          "tc": 2,
          "ti": 2,
          "tiPct": 100,
          "c3p": 0,
          "i3p": 2,
          "pct3p": 0,
          "ar3p": 50,
          "tlc": 0,
          "tli": 1,
          "tlPct": 0,
          "ftr": 25,
          "efgPct": 50,
          "tsPct": 45.05,
          "tovPct": 0,
          "rd": 0,
          "ro": 0,
          "rt": 0,
          "as": 0,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 0,
          "fpr": 1,
          "pt": 4,
          "ptsTot": 2
        },
        {
          "id": "row_somisa_33_1790960070570_0.9646842050527081",
          "playerNumber": 33,
          "playerName": "ANDOLLO, SEBASTIAN",
          "playerPosition": "Alero",
          "min": "15:46",
          "minSeconds": 946,
          "tc": 0,
          "ti": 1,
          "tiPct": 0,
          "c3p": 1,
          "i3p": 2,
          "pct3p": 50,
          "ar3p": 66.7,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 50,
          "tsPct": 50,
          "tovPct": 0,
          "rd": 3,
          "ro": 0,
          "rt": 3,
          "as": 2,
          "rec": 1,
          "per": 0,
          "tap": 0,
          "fpc": 2,
          "fpr": 2,
          "pt": 3,
          "ptsTot": 7
        },
        {
          "id": "row_somisa_88_1790960070570_0.809068815227121",
          "playerNumber": 88,
          "playerName": "MENA, SEBASTIAN ALEJANDRO",
          "playerPosition": "Alero",
          "min": "24:55",
          "minSeconds": 1495,
          "tc": 2,
          "ti": 2,
          "tiPct": 100,
          "c3p": 0,
          "i3p": 3,
          "pct3p": 0,
          "ar3p": 60,
          "tlc": 4,
          "tli": 6,
          "tlPct": 66.67,
          "ftr": 120,
          "efgPct": 40,
          "tsPct": 52.36,
          "tovPct": 0,
          "rd": 4,
          "ro": 2,
          "rt": 6,
          "as": 2,
          "rec": 1,
          "per": 0,
          "tap": 0,
          "fpc": 4,
          "fpr": 8,
          "pt": 8,
          "ptsTot": 16
        }
      ],
      "opponentStats": {
        "pts": 52,
        "tc": 15,
        "ti": 38,
        "c3p": 4,
        "i3p": 19,
        "tlc": 10,
        "tli": 16,
        "rd": 28,
        "ro": 5,
        "as": 9,
        "rec": 2,
        "per": 7,
        "tap": 2,
        "fpc": 23
      },
      "shots": []
    },
    {
      "id": "match_excel_1790960065137",
      "title": "SOMISA (San Nicolas) vs COLON (Chivilcoy)",
      "date": "2026-10-02",
      "competition": "LIGA PCIAL FBB (Masculino 2026)",
      "season": "2026",
      "homeAway": "home",
      "myTeamName": "SOMISA (San Nicolas)",
      "opponentName": "COLON (Chivilcoy)",
      "scoreMyTeam": 85,
      "scoreOpponent": 63,
      "notes": "Importado desde planilla Excel oficial.",
      "rows": [
        {
          "id": "row_somisa_2_1790960063861_0.9534851423164324",
          "playerNumber": 2,
          "playerName": "PEDEMONTE, JUAN PABLO",
          "playerPosition": "Alero",
          "min": "22:33",
          "minSeconds": 1353,
          "tc": 0,
          "ti": 1,
          "tiPct": 0,
          "c3p": 1,
          "i3p": 3,
          "pct3p": 33.33,
          "ar3p": 75,
          "tlc": 4,
          "tli": 6,
          "tlPct": 66.67,
          "ftr": 150,
          "efgPct": 37.5,
          "tsPct": 52.71,
          "tovPct": 0,
          "rd": 6,
          "ro": 1,
          "rt": 7,
          "as": 1,
          "rec": 1,
          "per": 0,
          "tap": 0,
          "fpc": 1,
          "fpr": 4,
          "pt": 7,
          "ptsTot": 14
        },
        {
          "id": "row_somisa_4_1790960063861_0.8931440034665268",
          "playerNumber": 4,
          "playerName": "ZACCHERINI ROMERO, FABRICIO MATIAS",
          "playerPosition": "Alero",
          "min": "01:58",
          "minSeconds": 118,
          "tc": 0,
          "ti": 0,
          "tiPct": 0,
          "c3p": 0,
          "i3p": 0,
          "pct3p": 0,
          "ar3p": 0,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 0,
          "tsPct": 0,
          "tovPct": 0,
          "rd": 0,
          "ro": 0,
          "rt": 0,
          "as": 0,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 0,
          "fpr": 0,
          "pt": 0,
          "ptsTot": 0
        },
        {
          "id": "row_somisa_5_1790960063861_0.03236573729280934",
          "playerNumber": 5,
          "playerName": "GONZALEZ ROVEDA, LUCIO",
          "playerPosition": "Base",
          "min": "27:44",
          "minSeconds": 1664,
          "tc": 6,
          "ti": 10,
          "tiPct": 60,
          "c3p": 0,
          "i3p": 2,
          "pct3p": 0,
          "ar3p": 16.7,
          "tlc": 1,
          "tli": 3,
          "tlPct": 33.33,
          "ftr": 25,
          "efgPct": 50,
          "tsPct": 48.8,
          "tovPct": 18.38,
          "rd": 5,
          "ro": 0,
          "rt": 5,
          "as": 1,
          "rec": 0,
          "per": 3,
          "tap": 3,
          "fpc": 1,
          "fpr": 3,
          "pt": 13,
          "ptsTot": 13
        },
        {
          "id": "row_somisa_8_1790960063861_0.33357410720653213",
          "playerNumber": 8,
          "playerName": "BUALO, AGUSTIN",
          "playerPosition": "Base",
          "min": "28:58",
          "minSeconds": 1738,
          "tc": 1,
          "ti": 5,
          "tiPct": 20,
          "c3p": 3,
          "i3p": 5,
          "pct3p": 60,
          "ar3p": 50,
          "tlc": 5,
          "tli": 7,
          "tlPct": 71.43,
          "ftr": 70,
          "efgPct": 55,
          "tsPct": 61.16,
          "tovPct": 0,
          "rd": 10,
          "ro": 1,
          "rt": 11,
          "as": 3,
          "rec": 1,
          "per": 0,
          "tap": 0,
          "fpc": 2,
          "fpr": 4,
          "pt": 16,
          "ptsTot": 25
        },
        {
          "id": "row_somisa_9_1790960063861_0.7796049420123218",
          "playerNumber": 9,
          "playerName": "BROVARONE, FAUSTINO",
          "playerPosition": "Base",
          "min": "15:27",
          "minSeconds": 927,
          "tc": 1,
          "ti": 1,
          "tiPct": 100,
          "c3p": 1,
          "i3p": 3,
          "pct3p": 33.33,
          "ar3p": 75,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 62.5,
          "tsPct": 62.5,
          "tovPct": 0,
          "rd": 3,
          "ro": 0,
          "rt": 3,
          "as": 0,
          "rec": 1,
          "per": 0,
          "tap": 0,
          "fpc": 2,
          "fpr": 0,
          "pt": 5,
          "ptsTot": 5
        },
        {
          "id": "row_somisa_10_1790960063861_0.02661377364674522",
          "playerNumber": 10,
          "playerName": "VITANGELI, SANTINO",
          "playerPosition": "Escolta",
          "min": "07:35",
          "minSeconds": 455,
          "tc": 0,
          "ti": 0,
          "tiPct": 0,
          "c3p": 0,
          "i3p": 1,
          "pct3p": 0,
          "ar3p": 100,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 0,
          "tsPct": 0,
          "tovPct": 0,
          "rd": 0,
          "ro": 0,
          "rt": 0,
          "as": 0,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 0,
          "fpr": 0,
          "pt": 0,
          "ptsTot": -1
        },
        {
          "id": "row_somisa_11_1790960063861_0.996538386776636",
          "playerNumber": 11,
          "playerName": "RATTERO, RAMIRO",
          "playerPosition": "Alero",
          "min": "27:10",
          "minSeconds": 1630,
          "tc": 4,
          "ti": 6,
          "tiPct": 66.67,
          "c3p": 3,
          "i3p": 3,
          "pct3p": 100,
          "ar3p": 33.3,
          "tlc": 2,
          "tli": 2,
          "tlPct": 100,
          "ftr": 22.22,
          "efgPct": 94.44,
          "tsPct": 96.15,
          "tovPct": 16.84,
          "rd": 4,
          "ro": 1,
          "rt": 5,
          "as": 2,
          "rec": 1,
          "per": 2,
          "tap": 1,
          "fpc": 3,
          "fpr": 4,
          "pt": 19,
          "ptsTot": 25
        },
        {
          "id": "row_somisa_12_1790960063861_0.44880322387428784",
          "playerNumber": 12,
          "playerName": "URANGA, SEBASTIAN",
          "playerPosition": "Pívot",
          "min": "24:31",
          "minSeconds": 1471,
          "tc": 3,
          "ti": 6,
          "tiPct": 50,
          "c3p": 0,
          "i3p": 2,
          "pct3p": 0,
          "ar3p": 25,
          "tlc": 2,
          "tli": 2,
          "tlPct": 100,
          "ftr": 25,
          "efgPct": 37.5,
          "tsPct": 45.05,
          "tovPct": 0,
          "rd": 2,
          "ro": 1,
          "rt": 3,
          "as": 1,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 3,
          "fpr": 2,
          "pt": 8,
          "ptsTot": 6
        },
        {
          "id": "row_somisa_13_1790960063861_0.5853935046858425",
          "playerNumber": 13,
          "playerName": "VASSOLO, EMILIANO",
          "playerPosition": "Alero",
          "min": "11:01",
          "minSeconds": 661,
          "tc": 1,
          "ti": 3,
          "tiPct": 33.33,
          "c3p": 1,
          "i3p": 2,
          "pct3p": 50,
          "ar3p": 40,
          "tlc": 1,
          "tli": 2,
          "tlPct": 50,
          "ftr": 40,
          "efgPct": 50,
          "tsPct": 51.02,
          "tovPct": 14.53,
          "rd": 2,
          "ro": 0,
          "rt": 2,
          "as": 3,
          "rec": 2,
          "per": 1,
          "tap": 0,
          "fpc": 0,
          "fpr": 1,
          "pt": 6,
          "ptsTot": 9
        },
        {
          "id": "row_somisa_20_1790960063862_0.32581074757389716",
          "playerNumber": 20,
          "playerName": "MASCAZZINI, ALEJO BENJAMIN",
          "playerPosition": "Alero",
          "min": "01:58",
          "minSeconds": 118,
          "tc": 1,
          "ti": 1,
          "tiPct": 100,
          "c3p": 0,
          "i3p": 0,
          "pct3p": 0,
          "ar3p": 0,
          "tlc": 1,
          "tli": 3,
          "tlPct": 33.33,
          "ftr": 300,
          "efgPct": 100,
          "tsPct": 64.66,
          "tovPct": 0,
          "rd": 0,
          "ro": 0,
          "rt": 0,
          "as": 0,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 1,
          "fpr": 2,
          "pt": 3,
          "ptsTot": 2
        },
        {
          "id": "row_somisa_33_1790960063862_0.857016603473224",
          "playerNumber": 33,
          "playerName": "ANDOLLO, SEBASTIAN",
          "playerPosition": "Alero",
          "min": "10:11",
          "minSeconds": 611,
          "tc": 0,
          "ti": 1,
          "tiPct": 0,
          "c3p": 0,
          "i3p": 0,
          "pct3p": 0,
          "ar3p": 0,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 0,
          "tsPct": 0,
          "tovPct": 50,
          "rd": 3,
          "ro": 0,
          "rt": 3,
          "as": 1,
          "rec": 1,
          "per": 1,
          "tap": 1,
          "fpc": 1,
          "fpr": 0,
          "pt": 0,
          "ptsTot": 3
        },
        {
          "id": "row_somisa_88_1790960063862_0.6708851728924825",
          "playerNumber": 88,
          "playerName": "MENA, SEBASTIAN ALEJANDRO",
          "playerPosition": "Alero",
          "min": "20:49",
          "minSeconds": 1249,
          "tc": 3,
          "ti": 5,
          "tiPct": 60,
          "c3p": 0,
          "i3p": 0,
          "pct3p": 0,
          "ar3p": 0,
          "tlc": 2,
          "tli": 5,
          "tlPct": 40,
          "ftr": 100,
          "efgPct": 60,
          "tsPct": 55.56,
          "tovPct": 29.41,
          "rd": 5,
          "ro": 1,
          "rt": 6,
          "as": 0,
          "rec": 0,
          "per": 3,
          "tap": 0,
          "fpc": 2,
          "fpr": 4,
          "pt": 8,
          "ptsTot": 6
        }
      ],
      "opponentStats": {
        "pts": 63,
        "tc": 15,
        "ti": 35,
        "c3p": 8,
        "i3p": 30,
        "tlc": 9,
        "tli": 11,
        "rd": 29,
        "ro": 7,
        "as": 9,
        "rec": 7,
        "per": 8,
        "tap": 2,
        "fpc": 24
      },
      "shots": []
    },
    {
      "id": "match_excel_1790959044484",
      "title": "SOMISA (San Nicolas) vs GIMNASIA (Pergamino)",
      "date": "2026-10-02",
      "competition": "LIGA PCIAL FBB (Masculino 2026)",
      "season": "2026",
      "homeAway": "home",
      "myTeamName": "SOMISA (San Nicolas)",
      "opponentName": "GIMNASIA (Pergamino)",
      "scoreMyTeam": 83,
      "scoreOpponent": 71,
      "notes": "Importado desde planilla Excel oficial.",
      "rows": [
        {
          "id": "row_somisa_1_1790958818804_0.5562255857338327",
          "playerNumber": 1,
          "playerName": "PAEZ, FELIPE",
          "playerPosition": "Alero",
          "min": "00:00",
          "minSeconds": 0,
          "tc": 0,
          "ti": 0,
          "tiPct": 0,
          "c3p": 0,
          "i3p": 0,
          "pct3p": 0,
          "ar3p": 0,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 0,
          "tsPct": 0,
          "tovPct": 0,
          "rd": 0,
          "ro": 0,
          "rt": 0,
          "as": 0,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 0,
          "fpr": 0,
          "pt": 0,
          "ptsTot": 0
        },
        {
          "id": "row_somisa_2_1790958818804_0.8794579005346964",
          "playerNumber": 2,
          "playerName": "PEDEMONTE, JUAN PABLO",
          "playerPosition": "Alero",
          "min": "34:20",
          "minSeconds": 2060,
          "tc": 4,
          "ti": 4,
          "tiPct": 100,
          "c3p": 5,
          "i3p": 9,
          "pct3p": 55.56,
          "ar3p": 69.2,
          "tlc": 2,
          "tli": 2,
          "tlPct": 100,
          "ftr": 15.38,
          "efgPct": 88.46,
          "tsPct": 90.06,
          "tovPct": 12.59,
          "rd": 3,
          "ro": 0,
          "rt": 3,
          "as": 0,
          "rec": 0,
          "per": 2,
          "tap": 0,
          "fpc": 2,
          "fpr": 2,
          "pt": 25,
          "ptsTot": 21
        },
        {
          "id": "row_somisa_4_1790958818805_0.19030385449799425",
          "playerNumber": 4,
          "playerName": "ZACCHERINI ROMERO, FABRICIO MATIAS",
          "playerPosition": "Alero",
          "min": "06:34",
          "minSeconds": 394,
          "tc": 0,
          "ti": 0,
          "tiPct": 0,
          "c3p": 0,
          "i3p": 0,
          "pct3p": 0,
          "ar3p": 0,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 0,
          "tsPct": 0,
          "tovPct": 100,
          "rd": 1,
          "ro": 1,
          "rt": 2,
          "as": 0,
          "rec": 0,
          "per": 2,
          "tap": 0,
          "fpc": 2,
          "fpr": 0,
          "pt": 0,
          "ptsTot": -2
        },
        {
          "id": "row_somisa_5_1790958818805_0.8557596159265087",
          "playerNumber": 5,
          "playerName": "GONZALEZ ROVEDA, LUCIO",
          "playerPosition": "Base",
          "min": "36:13",
          "minSeconds": 2173,
          "tc": 6,
          "ti": 9,
          "tiPct": 66.67,
          "c3p": 2,
          "i3p": 4,
          "pct3p": 50,
          "ar3p": 30.8,
          "tlc": 2,
          "tli": 2,
          "tlPct": 100,
          "ftr": 15.38,
          "efgPct": 69.23,
          "tsPct": 72.05,
          "tovPct": 0,
          "rd": 7,
          "ro": 0,
          "rt": 7,
          "as": 5,
          "rec": 3,
          "per": 0,
          "tap": 0,
          "fpc": 3,
          "fpr": 4,
          "pt": 20,
          "ptsTot": 30
        },
        {
          "id": "row_somisa_7_1790958818805_0.9708831471975897",
          "playerNumber": 7,
          "playerName": "DIAZ, JAIME",
          "playerPosition": "Ala-Pívot",
          "min": "00:00",
          "minSeconds": 0,
          "tc": 0,
          "ti": 0,
          "tiPct": 0,
          "c3p": 0,
          "i3p": 0,
          "pct3p": 0,
          "ar3p": 0,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 0,
          "tsPct": 0,
          "tovPct": 0,
          "rd": 0,
          "ro": 0,
          "rt": 0,
          "as": 0,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 0,
          "fpr": 0,
          "pt": 0,
          "ptsTot": 0
        },
        {
          "id": "row_somisa_8_1790958818805_0.2018241881755204",
          "playerNumber": 8,
          "playerName": "BUALO, AGUSTIN",
          "playerPosition": "Base",
          "min": "31:03",
          "minSeconds": 1863,
          "tc": 2,
          "ti": 3,
          "tiPct": 66.67,
          "c3p": 3,
          "i3p": 10,
          "pct3p": 30,
          "ar3p": 76.9,
          "tlc": 1,
          "tli": 2,
          "tlPct": 50,
          "ftr": 15.38,
          "efgPct": 50,
          "tsPct": 50.43,
          "tovPct": 17.77,
          "rd": 6,
          "ro": 0,
          "rt": 6,
          "as": 3,
          "rec": 0,
          "per": 3,
          "tap": 0,
          "fpc": 1,
          "fpr": 3,
          "pt": 14,
          "ptsTot": 13
        },
        {
          "id": "row_somisa_9_1790958818805_0.595625079618223",
          "playerNumber": 9,
          "playerName": "BROVARONE, FAUSTINO",
          "playerPosition": "Base",
          "min": "17:02",
          "minSeconds": 1022,
          "tc": 0,
          "ti": 1,
          "tiPct": 0,
          "c3p": 1,
          "i3p": 4,
          "pct3p": 25,
          "ar3p": 80,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 30,
          "tsPct": 30,
          "tovPct": 16.67,
          "rd": 0,
          "ro": 1,
          "rt": 1,
          "as": 3,
          "rec": 1,
          "per": 1,
          "tap": 0,
          "fpc": 1,
          "fpr": 0,
          "pt": 3,
          "ptsTot": 2
        },
        {
          "id": "row_somisa_10_1790958818805_0.3933181928034486",
          "playerNumber": 10,
          "playerName": "VITANGELI, SANTINO",
          "playerPosition": "Escolta",
          "min": "00:00",
          "minSeconds": 0,
          "tc": 0,
          "ti": 0,
          "tiPct": 0,
          "c3p": 0,
          "i3p": 0,
          "pct3p": 0,
          "ar3p": 0,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 0,
          "tsPct": 0,
          "tovPct": 0,
          "rd": 0,
          "ro": 0,
          "rt": 0,
          "as": 0,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 0,
          "fpr": 0,
          "pt": 0,
          "ptsTot": 0
        },
        {
          "id": "row_somisa_11_1790958818805_0.9903155760792285",
          "playerNumber": 11,
          "playerName": "RATTERO, RAMIRO",
          "playerPosition": "Alero",
          "min": "19:50",
          "minSeconds": 1190,
          "tc": 1,
          "ti": 3,
          "tiPct": 33.33,
          "c3p": 1,
          "i3p": 3,
          "pct3p": 33.33,
          "ar3p": 50,
          "tlc": 2,
          "tli": 2,
          "tlPct": 100,
          "ftr": 33.33,
          "efgPct": 41.67,
          "tsPct": 50.87,
          "tovPct": 12.69,
          "rd": 4,
          "ro": 0,
          "rt": 4,
          "as": 1,
          "rec": 0,
          "per": 1,
          "tap": 0,
          "fpc": 5,
          "fpr": 2,
          "pt": 7,
          "ptsTot": 4
        },
        {
          "id": "row_somisa_12_1790958818805_0.4231948635384799",
          "playerNumber": 12,
          "playerName": "URANGA, SEBASTIAN",
          "playerPosition": "Pívot",
          "min": "27:40",
          "minSeconds": 1660,
          "tc": 0,
          "ti": 1,
          "tiPct": 0,
          "c3p": 0,
          "i3p": 3,
          "pct3p": 0,
          "ar3p": 75,
          "tlc": 2,
          "tli": 2,
          "tlPct": 100,
          "ftr": 50,
          "efgPct": 0,
          "tsPct": 20.49,
          "tovPct": 29.07,
          "rd": 3,
          "ro": 1,
          "rt": 4,
          "as": 2,
          "rec": 1,
          "per": 2,
          "tap": 0,
          "fpc": 3,
          "fpr": 4,
          "pt": 2,
          "ptsTot": 4
        },
        {
          "id": "row_somisa_20_1790958818805_0.3623709741753868",
          "playerNumber": 20,
          "playerName": "MASCAZZINI, ALEJO BENJAMIN",
          "playerPosition": "Alero",
          "min": "00:07",
          "minSeconds": 7,
          "tc": 0,
          "ti": 0,
          "tiPct": 0,
          "c3p": 0,
          "i3p": 0,
          "pct3p": 0,
          "ar3p": 0,
          "tlc": 0,
          "tli": 0,
          "tlPct": 0,
          "ftr": 0,
          "efgPct": 0,
          "tsPct": 0,
          "tovPct": 0,
          "rd": 0,
          "ro": 0,
          "rt": 0,
          "as": 0,
          "rec": 0,
          "per": 0,
          "tap": 0,
          "fpc": 0,
          "fpr": 0,
          "pt": 0,
          "ptsTot": 0
        },
        {
          "id": "row_somisa_33_1790958818805_0.5733591355045359",
          "playerNumber": 33,
          "playerName": "ANDOLLO, SEBASTIAN",
          "playerPosition": "Alero",
          "min": "27:06",
          "minSeconds": 1626,
          "tc": 5,
          "ti": 6,
          "tiPct": 83.33,
          "c3p": 0,
          "i3p": 0,
          "pct3p": 0,
          "ar3p": 0,
          "tlc": 2,
          "tli": 4,
          "tlPct": 50,
          "ftr": 66.67,
          "efgPct": 83.33,
          "tsPct": 77.32,
          "tovPct": 34.01,
          "rd": 8,
          "ro": 1,
          "rt": 9,
          "as": 3,
          "rec": 2,
          "per": 4,
          "tap": 0,
          "fpc": 2,
          "fpr": 3,
          "pt": 12,
          "ptsTot": 20
        }
      ],
      "opponentStats": {
        "pts": 71,
        "tc": 17,
        "ti": 33,
        "c3p": 9,
        "i3p": 31,
        "tlc": 10,
        "tli": 18,
        "rd": 22,
        "ro": 6,
        "as": 9,
        "rec": 13,
        "per": 11,
        "tap": 2,
        "fpc": 18
      },
      "shots": []
    }
  ]
};
